### ISSUE TITLE
Calling functions in LINQ queries has many errors

### ISSUE THREAD

**Issue by NetMage** [tpetricek/tomasp.net#37]
The article [Calling functions in LINQ queries](http://tomasp.net/blog/linq-expand.aspx/) has many typos and other errors in the beginning with the sample code.

For example, the text states "calls function MyTest" but the sample function is named "MyFunc" and the where clause actually calls an entirely different undefined function MyPriceFunc.

**Comment by tpetricek** [comment]
Thanks for reading and taking the time to report. However, given that the article is now some 17 years old, I'm probably not going to fix those (and leave it as it is). It may be worth tweaking the system to automatically add a warning when you open a very old article.

**Comment by NetMage** [comment]
:( I found the blog post from the [LINQKit page](https://www.albahari.com/nutshell/linqkit.aspx) by Albahari so I expect it still gets some traffic...
